version: '3.8'
services:

  postgresql:
    container_name: userPostgresDB
    image: postgres:10.4
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user_DB
    networks:
      - comment

networks:
  comment:
    driver: bridge